### ISSUE TITLE
Question: Post header - X min read, Suggest an Edit, Issue? Question? 

### ISSUE THREAD

**Issue by W0GER** [SeanKilleen/seankilleen.github.io#833]
Sean -- 

What plug-in (or how) are you using to generate the post header? 

Example: 

> 4 minute read | [ Suggest an edit](https://github.com/SeanKilleen/seankilleen.github.io/edit/main/_posts/2023-08-10-my-process-for-reviewing-pull-requests.md) | [ Issue? Question?](https://github.com/SeanKilleen/seankilleen.github.io/issues/new?labels=FromTheSite)

**Comment by SeanKilleen** [comment]
@W0GER I use the minimal-mistakes theme for the blog. They have an include file that I override. In the `_includes` folder, you'll see there's a `post__meta__witheditlinks.html`. I added the links in there. I then also updated the `page__hero.html` include to use that instead of a reference to `post__meta`. I added it as an override in the `single.html` page in `_layouts` as well.

**Comment by SeanKilleen** [comment]
Going to close this now, but let me know here if you have any further questions and I'm happy to help!

**Comment by W0GER** [comment]
Thanks, that gives me the pointers to figure out how to bring it into my theme.
